/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DatePicker {
        "disable": boolean;
        "error": boolean;
        "lock": boolean;
        "maxdatecurrent": boolean;
        "placeholder": string;
        "selectedDate": boolean;
        "startview": string;
        "value": any;
    }
    interface MDatepicker {
        "disable": boolean;
        "error": boolean;
        "errortext": string;
        "label": string;
        "lock": boolean;
        "placeholder": string;
        "startview": string;
        "value": string;
    }
}
declare global {
    interface HTMLDatePickerElement extends Components.DatePicker, HTMLStencilElement {
    }
    var HTMLDatePickerElement: {
        prototype: HTMLDatePickerElement;
        new (): HTMLDatePickerElement;
    };
    interface HTMLMDatepickerElement extends Components.MDatepicker, HTMLStencilElement {
    }
    var HTMLMDatepickerElement: {
        prototype: HTMLMDatepickerElement;
        new (): HTMLMDatepickerElement;
    };
    interface HTMLElementTagNameMap {
        "date-picker": HTMLDatePickerElement;
        "m-datepicker": HTMLMDatepickerElement;
    }
}
declare namespace LocalJSX {
    interface DatePicker {
        "disable"?: boolean;
        "error"?: boolean;
        "lock"?: boolean;
        "maxdatecurrent"?: boolean;
        "onNewValue"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "selectedDate"?: boolean;
        "startview"?: string;
        "value"?: any;
    }
    interface MDatepicker {
        "disable"?: boolean;
        "error"?: boolean;
        "errortext"?: string;
        "label"?: string;
        "lock"?: boolean;
        "placeholder"?: string;
        "startview"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "date-picker": DatePicker;
        "m-datepicker": MDatepicker;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "date-picker": LocalJSX.DatePicker & JSXBase.HTMLAttributes<HTMLDatePickerElement>;
            "m-datepicker": LocalJSX.MDatepicker & JSXBase.HTMLAttributes<HTMLMDatepickerElement>;
        }
    }
}
